# References:
# 1. Donot expose any other ports besides XX02, use reverse tunnelling instead.
# 2. Limit devices when need
# 3. Limit Home directory expansion.
# 4. Limit net memory 63.8 >> 60.

version: '2.3'
services:
  # nvidia:
  #   image: nvidia/cuda
  #   runtime: nvidia
  #   command: bash
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=2
  #   tty: true
  #   stdin_open: true

# Varun torch
  varun_torch:
    image: iitmcvg/torch
    build:
      context: .
      dockerfile: torch-Dockerfile
    runtime: nvidia
    command: zsh
    shm_size: 59G
    ports:
      - "1002:22"
    volumes:
      - /media/home/varun:/home/varun
      - /media/ssda:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2/varun:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=varun

# Lokesh
  lokesh:
    image: iitmcvg/workstation
    build: 
      context: .
      dockerfile: tf-Dockerfile
    runtime: nvidia
    command: bash
    ports:
      - "2002:22"                                                                                                                         
    volumes:
      - /media/home/lokesh:/home/lokesh
      - /media/ssda/lokesh:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2/lokesh:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=vighnesh
  
# Rajat
  rajat:
    image: iitmcvg/torch
    build:
      context: .
      dockerfile: torch/Dockerfile
    runtime: nvidia
    command: bash
    ports:
      - "5002:22"
    volumes:
      - /media/home/rajat:/home/rajat
      - /media/ssda/rajat:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2/rajat:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=rajat

# Minio Servers
  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - /media/iitmcvg/VARUN_CVI:/data
      - /mnt/config:/root/.minio 
    tty: true
    stdin_open: false
    environment:
      - TZ="Asia/Kolkata"
      - "MINIO_SECRET_KEY=iitmcvg/minio/usb1"
      - "MINIO_ACCESS_KEY=iitmcvg"

# Sumanth
  sumanth:
    image: iitmcvg/workstation
    build:
      context: .
      dockerfile: torch-Dockerfile
    runtime: nvidia
    command: bash
    ports:
      - "4002:22"
    volumes:
      - /media/home/sumanth:/home/vighnesh
      - /media/ssda/sumanth:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2/sumanth:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=sumanth
